#
# downloads.yml - Use the EAD's <unitid> as the primary key and
#                 provide the PDF and/or EAD (.xml) links. The
#                 size value should be a String (shown as-is) or
#                 the number of bytes in the download.
#               - Pass a template key to use a formatted string
#                 which interpolates document accessors into the
#                 url using the %{accessor} syntax.
#               - Pass a size_accessor key to pull the size of
#                 the file from an accessor in the solr document
#

#  Add this to your apache config for the download button to work
#   Alias /ead /<location-to-eads>/eads
#    <Directory /<location-to-eads>/eads>
#        Options none
#        Require all granted
#    </Directory>



sample_unitid:
 # pdf:
 #   href: 'http://example.com/sample.pdf'
 #   size: '1.23MB'
  ead:
    href: 'http://arclight.senylrc.org/search/xml/sample.xml'
    size: 123456
    # size_accessor: 'level'
default:
  disabled: false
#  pdf:
 #   template: 'http://example.com/%{unitid}.pdf'
  ead:
    template: 'https://beta.empireadc.org/ead/%{repository_id}/%{eadid}.xml'

